/* 図解・フロー（#046〜#060）— 番号・名前・動きは変えない。新しいシーンは #151 から */
MOTION.add("図解・フロー", [
 {id:46, name:"縦型3ステップ", pal:"zanzibar", loop:5000,
  desc:"ノードと点線が上から順につながり、最後のステップが光って強調。",
  html:`<div class="center s-flow">
    <div class="ttl">使い方は3ステップ</div>
    <div class="nd" style="--d:.4s"><i>1</i>シーンを選ぶ</div>
    <div class="ln" style="--d:.8s"></div>
    <div class="nd" style="--d:1.1s"><i>2</i>文字と色を変える</div>
    <div class="ln" style="--d:1.5s"></div>
    <div class="nd on hl" style="--d:1.8s"><i>3</i>動画で書き出す</div>
    </div>`},
{ id:47, pal:"madeira", name:"横型フロー", desc:"3つの箱が矢印でつながりながら左から右へ進む。", loop:4600,
  css:`.f1 .fl{display:flex;align-items:center;gap:1.4cqw}.f1 .bx{width:22cqw;height:22cqw;border-radius:4cqw;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:1cqw;text-align:center}.f1 svg{width:6cqw}`,
  html:`<div class="center f1 fc" style="gap:7cqw"><div class="h2 a fu">依頼から公開まで</div><div class="fl">${['相談','制作','公開'].map((t,i)=>`${i?`<svg viewBox="0 0 10 10" class="a sl" style="${D(.3,i,.5)};--du:.3s"><path d="M1 5h7M5 2l3 3-3 3" fill="none" stroke="var(--acc)" stroke-width="1.6"/></svg>`:''}<div class="bx ${i==2?'bxa':'bxs'} a pp" style="${D(.4,i,.5)}"><span class="en" style="font-size:7cqw">${i+1}</span><span class="sm">${t}</span></div>`).join("")}</div></div>` },
{ id:48, pal:"lemon", name:"循環サイクル", desc:"4つのノードが円周上に並び、ハイライトが順にぐるぐる回る。", loop:6000,
  css:`.f2 .cy{position:relative;width:76cqw;height:76cqw}.f2 .ring{position:absolute;inset:9cqw;border-radius:50%;border:.8cqw dashed var(--sub);animation:spin 12s linear infinite}.f2 .nd{position:absolute;width:24cqw;height:24cqw;border-radius:50%;display:grid;place-items:center;text-align:center;background:var(--surf);color:var(--onSurf);translate:-50% -50%}.f2 .nd.on{background:var(--acc);color:var(--onAcc);translate:-50% -50%;scale:1.12;transition:.3s}.f2 .ct{position:absolute;inset:0;display:grid;place-items:center}`,
  html:`<div class="center f2 fc"><div class="cy a zo"><div class="ring"></div><div class="ct h3">PDCA</div>${[['計画',50,12],['実行',88,50],['評価',50,88],['改善',12,50]].map(([t,x,y])=>`<div class="nd h3" style="left:${x}%;top:${y}%">${t}</div>`).join("")}</div></div>`,
  init(el){ const n=[...el.querySelectorAll(".nd")]; every(el,700,i=>n.forEach((x,k)=>x.classList.toggle("on",k===i%4)),500); } },
{ id:49, pal:"tanzania", name:"ベン図", desc:"2つの円が左右から近づいて重なり、重なった部分にキーワード。", loop:4600,
  css:`.f3 .vn{position:relative;width:86cqw;height:52cqw}.f3 .cl{position:absolute;top:0;width:52cqw;height:52cqw;border-radius:50%;display:flex;align-items:center;padding:0 7cqw;mix-blend-mode:normal}.f3 .l{left:0;background:color-mix(in srgb,var(--sub) 70%,transparent);animation:f3l .9s cubic-bezier(.2,.8,.2,1) .3s both}.f3 .r{right:0;justify-content:flex-end;background:color-mix(in srgb,var(--acc) 70%,transparent);animation:f3r .9s cubic-bezier(.2,.8,.2,1) .3s both}@keyframes f3l{from{transform:translateX(-20cqw);opacity:0}}@keyframes f3r{from{transform:translateX(20cqw);opacity:0}}.f3 .mid{position:absolute;inset:0;display:grid;place-items:center}`,
  html:`<div class="center f3 fc" style="gap:6cqw"><div class="vn"><div class="cl l sm">デザイン</div><div class="cl r sm">AI</div><div class="mid"><span class="h3 a pp" style="--d:1.2s">最速<br>制作</span></div></div><div class="sm sb a fu" style="--d:1.5s">ふたつが重なるところに価値がある</div></div>` },
{ id:50, pal:"maldives", name:"ピラミッド", desc:"3段のピラミッドが下から積み上がり、頂点を強調。", loop:4600,
  css:`.f4 .py{display:flex;flex-direction:column-reverse;align-items:center;gap:1.4cqw}.f4 .lv{height:15cqw;display:grid;place-items:center;clip-path:polygon(var(--i) 0,calc(100% - var(--i)) 0,100% 100%,0 100%)}`,
  html:`<div class="center f4 fc" style="gap:6cqw"><div class="h2 a fu">集客の3段階</div><div class="py">${[['認知',80,'bxs'],['興味',60,'bxs'],['購入',40,'bxa']].map(([t,w,c],i)=>`<div class="lv ${c} h3 a su" style="width:${w}cqw;--i:${i==2?'50%':'10cqw'};${i==2?'clip-path:polygon(50% 0,50% 0,100% 100%,0 100%);height:22cqw;padding-top:6cqw':''};${D(.3,i,.4)}">${t}</div>`).join("")}</div></div>` },
{ id:51, pal:"glowup", name:"マインドマップ", desc:"中央のテーマから枝が伸び、周りにキーワードが現れる。", loop:5000,
  css:`.f5 .mm{position:relative;width:86cqw;height:110cqw}.f5 svg{position:absolute;inset:0;width:100%;height:100%}.f5 .c{position:absolute;left:50%;top:50%;translate:-50% -50%;width:28cqw;height:28cqw;border-radius:50%;display:grid;place-items:center}.f5 .k{position:absolute;translate:-50% -50%;padding:2cqw 4cqw;border-radius:9cqw;white-space:nowrap}`,
  html:`<div class="center f5"><div class="mm"><svg viewBox="0 0 86 110">${[[20,18],[70,22],[78,60],[64,94],[16,88],[8,52]].map(([x,y],i)=>`<line x1="43" y1="55" x2="${x}" y2="${y}" stroke="var(--sub)" stroke-width=".7" pathLength="100" class="dw" style="${D(.6,i,.1)};--du:.5s"/>`).join("")}</svg>
  <div class="c bxa h3 a zo" style="--d:.2s">AI活用</div>${[['文章',20,18],['画像',70,22],['動画',78,60],['自動化',64,94],['分析',16,88],['音声',8,52]].map(([t,x,y],i)=>`<div class="k bxs sm a pp" style="left:${x/86*100}%;top:${y/110*100}%;${D(1,i,.1)}">${t}</div>`).join("")}</div></div>` },
{ id:52, pal:"clustr", name:"ビフォー→アフター図", desc:"左の状態から矢印が伸び、右の改善後の状態が現れる。", loop:4600,
  css:`.f6 .pn{width:34cqw;height:46cqw;border-radius:4cqw;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2cqw;text-align:center;padding:3cqw}.f6 svg{width:12cqw}`,
  html:`<div class="center f6 fc" style="gap:5cqw"><div class="fr" style="gap:2cqw"><div class="pn bxs a sl" style="--d:.2s"><span class="sm" style="opacity:.7">BEFORE</span><span class="h3">月5件<br>問い合わせ</span></div>
  <svg viewBox="0 0 20 10"><path d="M1 5h16M13 1l4 4-4 4" fill="none" stroke="var(--acc)" stroke-width="1.6" pathLength="100" class="dw" style="--d:.8s;--du:.5s"/></svg>
  <div class="pn bxa a zo" style="--d:1.3s"><span class="sm" style="opacity:.8">AFTER</span><span class="h3">月32件<br>問い合わせ</span></div></div><div class="sm sb a fu" style="--d:1.7s">サイトリニューアル 3か月後</div></div>` },
{ id:53, pal:"ibiza", name:"ツリー（組織図）", desc:"上の箱から線が分岐し、下段の箱が順に追加される。", loop:4600,
  css:`.f7 .tr{position:relative;width:84cqw;height:70cqw}.f7 svg{position:absolute;inset:0;width:100%;height:100%}.f7 .bx{position:absolute;translate:-50% 0;padding:3cqw 4cqw;border-radius:3cqw;white-space:nowrap}`,
  html:`<div class="center f7"><div class="tr"><svg viewBox="0 0 84 70" fill="none" stroke="var(--sub)" stroke-width=".6"><path d="M42 14V26M14 26H70M14 26V40M42 26V40M70 26V40" pathLength="100" class="dw" style="--d:.5s;--du:.7s"/><path d="M14 50V58M8 58H20" pathLength="100" class="dw" style="--d:1.5s;--du:.4s"/></svg>
  <div class="bx bxa h3 a pp" style="left:50%;top:0;--d:.2s">代表</div>${[['デザイン',14],['開発',42],['広報',70]].map(([t,x],i)=>`<div class="bx bxs sm a pp" style="left:${x/84*100}%;top:${40/70*100}%;${D(1,i,.15)}">${t}</div>`).join("")}<div class="bx sm sb a fu" style="left:${14/84*100}%;top:${60/70*100}%;--d:1.8s">AIアシスタント</div></div></div>` },
{ id:54, pal:"cherry", name:"2×2マトリクス", desc:"縦横の軸が引かれ、ドットが目標の象限へ移動する。", loop:5000,
  css:`.f8 .mx{position:relative;width:76cqw;height:76cqw}.f8 .ax{position:absolute;background:var(--ink)}.f8 .x{left:0;right:0;top:50%;height:.5cqw;transform-origin:left;animation:growX .6s ease .2s both}.f8 .y{top:0;bottom:0;left:50%;width:.5cqw;transform-origin:bottom;animation:growY .6s ease .4s both}.f8 .q{position:absolute;width:50%;height:50%;display:grid;place-items:center;text-align:center}.f8 .dt{position:absolute;width:8cqw;height:8cqw;border-radius:50%;background:var(--acc);left:21%;top:71%;animation:f8 1.2s cubic-bezier(.5,0,.2,1) 1.4s both}@keyframes f8{to{left:71%;top:21%}}`,
  html:`<div class="center f8 fc" style="gap:4cqw"><div class="mx"><div class="ax x"></div><div class="ax y"></div>${[['手間大・効果大',0,0],['手間小・効果大',50,0],['手間大・効果小',0,50],['手間小・効果小',50,50]].map(([t,x,y],i)=>`<div class="q sm ${i==1?'ac':'sb'} a fi" style="left:${x}%;top:${y}%;${D(.8,i,.1)}">${t}</div>`).join("")}<div class="dt"></div></div><div class="h3 a fu" style="--d:2.4s">AI化はここ！</div></div>` },
{ id:55, pal:"mp213", name:"YES/NO分岐", desc:"質問から2方向に矢印が分かれ、結果が表示される。診断コンテンツに。", loop:5000,
  css:`.f9 .q{padding:4cqw 6cqw;border-radius:4cqw}.f9 .br{display:flex;gap:6cqw}.f9 .bc{display:flex;flex-direction:column;align-items:center;gap:2cqw}.f9 .rs{width:34cqw;padding:4cqw;border-radius:4cqw;text-align:center}.f9 .ln{width:.6cqw;height:9cqw;background:var(--sub);transform-origin:top;animation:growY .4s ease var(--d) both}`,
  html:`<div class="center f9 fc" style="gap:3cqw"><div class="q bxs h3 a pp" style="--d:.2s">毎月サイトを更新する？</div><div class="br">${[['YES','STUDIO\nがおすすめ','bxa'],['NO','ペライチ\nで十分','bxs']].map(([a,b,c],i)=>`<div class="bc"><div class="ln" style="${D(.7,i,.2)}"></div><span class="sm en ${i?'sb':'ac'} a fi" style="${D(1,i,.2)}">${a}</span><div class="rs ${c} sm a pp" style="${D(1.3,i,.25)};white-space:pre-line">${b}</div></div>`).join("")}</div></div>` },
{ id:56, pal:"zanzibar", name:"階段ステップ", desc:"段差が1段ずつ積み上がり、頂上にゴールの旗。", loop:4800,
  css:`.f10 .st{display:flex;align-items:flex-end;gap:1cqw}.f10 .sp{width:17cqw;border-radius:2cqw 2cqw 0 0;display:flex;align-items:flex-start;justify-content:center;padding-top:2cqw}.f10 svg{width:12cqw;margin-left:auto;margin-right:3cqw}`,
  html:`<div class="center f10 fc" style="gap:2cqw"><svg viewBox="0 0 20 24" class="a dp" style="--d:1.8s"><path d="M3 23V2" stroke="var(--ink)" stroke-width="1.6"/><path d="M4 3h13l-3 4 3 4H4z" fill="var(--acc)"/></svg><div class="st">${[['基礎',18],['実践',32],['応用',46],['独立',60]].map(([t,h],i)=>`<div class="sp ${i==3?'bxa':'bxs'} sm gy" style="height:${h}cqw;${D(.3,i,.3)}">${t}</div>`).join("")}</div><div class="h3 a fu" style="--d:2s;margin-top:3cqw">4ステップで独立へ</div></div>` },
{ id:57, pal:"madeira", name:"ハブ＆スポーク", desc:"中心から放射状に線が伸び、周囲のサービスとつながる。", loop:5000,
  css:`.f11 .hb{position:relative;width:84cqw;height:84cqw}.f11 svg{position:absolute;inset:0;width:100%;height:100%}.f11 .c{position:absolute;left:50%;top:50%;width:26cqw;height:26cqw;translate:-50% -50%;border-radius:6cqw;display:grid;place-items:center}.f11 .n{position:absolute;width:18cqw;height:18cqw;border-radius:50%;translate:-50% -50%;display:grid;place-items:center;font-size:3.2cqw;font-weight:700}`,
  html:`<div class="center f11"><div class="hb">${(()=>{const p=[0,1,2,3,4,5].map(i=>{const a=i/6*Math.PI*2-Math.PI/2;return[50+38*Math.cos(a),50+38*Math.sin(a)]});return `<svg viewBox="0 0 100 100">${p.map(([x,y],i)=>`<line x1="50" y1="50" x2="${x}" y2="${y}" stroke="var(--sub)" stroke-width=".6" pathLength="100" class="dw" style="${D(.5,i,.08)};--du:.5s"/>`).join("")}</svg><div class="c bxa h3 a zo" style="--d:.2s">n8n</div>${p.map(([x,y],i)=>`<div class="n bxs a pp" style="left:${x}%;top:${y}%;${D(.9,i,.08)}">${['Gmail','Slack','Notion','Drive','LINE','X'][i]}</div>`).join("")}`})()}</div></div>` },
{ id:58, pal:"lemon", name:"横タイムライン", desc:"横線が引かれ、マイルストーンが上下交互に立ち上がる。", loop:5000,
  css:`.f12 .tl{position:relative;width:88cqw;height:70cqw}.f12 .ln{position:absolute;left:0;right:0;top:50%;height:.6cqw;background:var(--ink);transform-origin:left;animation:growX 1.4s ease .2s both}.f12 .ms{position:absolute;translate:-50% 0;display:flex;flex-direction:column;align-items:center;gap:1.4cqw;width:24cqw;text-align:center}.f12 .dt{width:4cqw;height:4cqw;border-radius:50%;background:var(--acc)}`,
  html:`<div class="center f12"><div class="tl"><div class="ln"></div>${[['4月','企画',12],['6月','制作',38],['8月','公開',62],['10月','集客',88]].map(([a,b,x],i)=>`<div class="ms a ${i%2?'fu':'sd'}" style="left:${x}%;${i%2?'top:calc(50% - 2cqw)':'bottom:calc(50% - 2cqw);flex-direction:column-reverse'};${D(.5,i,.3)}"><span class="dt"></span><span class="sm en ac">${a}</span><span class="h3">${b}</span></div>`).join("")}</div></div>` },
{ id:59, pal:"tanzania", name:"天秤の比較", desc:"天秤が揺れて、重いほうへ傾く。選択の決め手を見せる。", loop:5000,
  css:`.f13 svg{width:84cqw;overflow:visible}.f13 .bm{transform-origin:50px 30px;animation:f13 1.6s cubic-bezier(.3,1.6,.5,1) .6s both}@keyframes f13{0%{transform:rotate(0)}30%{transform:rotate(-6deg)}100%{transform:rotate(12deg)}}`,
  html:`<div class="center f13 fc" style="gap:4cqw"><svg viewBox="0 0 100 80"><path d="M50 30V74M36 76h28" stroke="var(--ink)" stroke-width="2" stroke-linecap="round"/><g class="bm"><line x1="10" y1="30" x2="90" y2="30" stroke="var(--ink)" stroke-width="2" stroke-linecap="round"/><path d="M10 30l-8 16h16zM90 30l-8 16h16z" fill="none" stroke="var(--sub)" stroke-width="1"/><rect x="0" y="46" width="20" height="6" rx="2" fill="var(--sub)"/><rect x="80" y="40" width="20" height="12" rx="2" fill="var(--acc)"/><text x="10" y="62" text-anchor="middle" font-size="5" font-weight="700" fill="var(--ink)">価格</text><text x="90" y="62" text-anchor="middle" font-size="5" font-weight="700" fill="var(--ink)">スピード</text></g><circle cx="50" cy="30" r="3" fill="var(--ink)"/></svg><div class="h3 a fu" style="--d:2s">決め手は「速さ」</div></div>` },
{ id:60, pal:"maldives", name:"歯車の連動", desc:"大小の歯車がかみ合って回り続ける。仕組み・連携の説明に。", loop:8000,
  css:`.f14 svg{width:80cqw}.f14 .gA{transform-origin:35px 40px;animation:spin 6s linear infinite}.f14 .gB{transform-origin:72px 62px;animation:spin 4s linear infinite reverse}`,
  html:`<div class="center f14 fc" style="gap:5cqw"><svg viewBox="0 0 100 90" class="a zo">${(()=>{const gear=(cx,cy,r,n,c,cls)=>{let d='';for(let i=0;i<n;i++){const a=i/n*Math.PI*2;d+=`<rect x="${cx-3}" y="${cy-r-6}" width="6" height="8" rx="1" fill="${c}" transform="rotate(${a*180/Math.PI} ${cx} ${cy})"/>`}return `<g class="${cls}">${d}<circle cx="${cx}" cy="${cy}" r="${r}" fill="${c}"/><circle cx="${cx}" cy="${cy}" r="${r*.35}" fill="var(--bg)"/></g>`};return gear(35,40,22,10,'var(--acc)','gA')+gear(72,62,14,7,'var(--sub)','gB')})()}</svg><div class="h2 a fu" style="--d:.3s">ツール同士を自動連携</div></div>` },
]);
