/* チャット・会話（#076〜#090）— 番号・名前・動きは変えない。新しいシーンは #151 から */
MOTION.add("チャット・会話", [
 {id:76, name:"チャット吹き出し", pal:"cherry", loop:6000,
  desc:"相手→自分の順に吹き出しがポップ。入力中インジケーターから返信へ。",
  props:{ name:"YOUR NAME", status:"オンライン", question:"これ、どうやって作ったの？", answer:"ブラウザだけで5分！", reply:"え、すごい…教えて！" },
  html:p=>`<div class="center s-chat">
    <div class="head"><div class="av">${[...p.name][0]}</div><div class="nm">${p.name}<small>${p.status}</small></div></div>
    <div class="msg l" style="--d:.5s">${p.question}</div>
    <div class="msg r" style="--d:1.3s">${p.answer}</div>
    <div class="msg l typing" style="--d:2.1s" data-typing><i></i><i></i><i></i></div>
    </div>`,
  init(el,p){
    setTimeout(()=>{ const t=el.querySelector("[data-typing]"); if(!t) return;
      t.className="msg l"; t.style.cssText="--d:0s"; t.textContent=p.reply; },3400);
  }},
{ id:77, pal:"madeira", name:"既読つきメッセージ", desc:"送ったメッセージの横に時間と「既読」がつく、トーク画面風。", loop:5000,
  css:`.q1 .mt{display:flex;align-items:flex-end;gap:2cqw;align-self:flex-end}.q1 .rd{font-size:2.8cqw;line-height:1.3;text-align:right;opacity:.7}`,
  props:{ message:"明日の打ち合わせ、何時にする？", reply:"10時でどうですか？", answer:"OK！よろしくね", time:"21:04" },
  html:p=>`<div class="chat q1"><div class="bbl bl a pp" style="--d:.3s">${p.message}</div><div class="mt"><span class="rd"><span class="a fi" style="--d:1.6s;display:block">既読</span>${p.time}</span><div class="bbl bR a pp" style="--d:1s">${p.reply}</div></div><div class="bbl bl a pp" style="--d:2.2s">${p.answer}</div></div>` },
{ id:78, pal:"lemon", name:"通知バナー", desc:"画面上部からプッシュ通知が滑り降り、軽く揺れて止まる。", loop:4600,
  css:`.q2 .nt{position:absolute;top:16cqw;left:6cqw;right:6cqw;border-radius:5cqw;padding:4cqw;display:flex;gap:3cqw;align-items:center;box-shadow:0 3cqw 8cqw rgba(0,0,0,.25)}.q2 .ap{width:11cqw;height:11cqw;border-radius:3cqw}`,
  props:{ app:"Instagram", text:"新しい問い合わせが3件あります", title:"通知が", accent:"止まらない" },
  html:p=>`<div class="center q2"><div class="nt bxs a sd" style="--d:.3s;--ez:cubic-bezier(.3,1.4,.5,1);--du:.7s"><div class="ap bxa"></div><div style="flex:1"><div class="sm" style="display:flex;justify-content:space-between"><b>${p.app}</b><span style="opacity:.6">今</span></div><div class="sm" style="opacity:.85">${p.text}</div></div></div><div class="h1 a fu" style="--d:1.2s;text-align:center">${p.title}<br><span class="ac">${p.accent}</span></div></div>` },
{ id:79, pal:"tanzania", name:"いいね数が増えるコメント", desc:"コメントが表示され、ハートといいね数がどんどん増える。", loop:5000,
  css:`.q3 .cm{width:84cqw;border-radius:4cqw;padding:5cqw;display:flex;gap:3cqw}.q3 .lk{display:flex;align-items:center;gap:1.6cqw;margin-top:2cqw;color:var(--acc)}.q3 svg{width:5cqw;fill:var(--acc)}.q3 .hb{animation:pulse .5s ease infinite}`,
  props:{ user:"mika_design", comment:"この投稿、保存しました！めちゃくちゃわかりやすい", likes:2480 },
  html:p=>`<div class="center q3"><div class="cm bxs a fu" style="--d:.2s"><div class="avt bxa">${[...p.user][0].toUpperCase()}</div><div><div class="sm" style="opacity:.7">${p.user}</div><div class="h3">${p.comment}</div><div class="lk sm en"><svg viewBox="0 0 24 24" class="hb"><path d="M12 21s-7-4.5-9.5-9A5 5 0 0 1 12 6a5 5 0 0 1 9.5 6C19 16.5 12 21 12 21z"/></svg><span data-n>0</span></div></div></div></div>`,
  init(el,p){ countUp(el.querySelector("[data-n]"),num(p.likes),3000,600,fmtc); } },
{ id:80, pal:"maldives", name:"ボイスメッセージ", desc:"音声メッセージの波形が左から再生されるように色づく。", loop:5000,
  css:`.q4 .vm{display:flex;align-items:center;gap:3cqw;padding:4cqw 5cqw;border-radius:9cqw}.q4 .pl{width:10cqw;height:10cqw;border-radius:50%;display:grid;place-items:center}.q4 .wv{display:flex;align-items:center;gap:.9cqw;height:10cqw}.q4 .wv i{width:1.2cqw;border-radius:1cqw;background:currentColor;opacity:.35;transition:opacity .1s}.q4 .wv i.on{opacity:1}`,
  props:{ length:"0:12", reply:"声で聞くとわかりやすい！" },
  html:p=>`<div class="chat q4"><div class="vm bR a pp" style="--d:.2s"><div class="pl" style="background:var(--onAcc);color:var(--acc)">▶</div><div class="wv">${[3,6,9,5,8,10,7,4,9,6,3,7,10,5,8,4,6,3].map(h=>`<i style="height:${h}cqw"></i>`).join("")}</div><span class="sm en">${p.length}</span></div><div class="bbl bl a pp" style="--d:3.2s">${p.reply}</div></div>`,
  init(el){ const b=[...el.querySelectorAll(".wv i")]; every(el,140,i=>{ if(i<b.length) b[i].classList.add("on"); },600); } },
{ id:81, pal:"glowup", name:"AIチャット回答", desc:"質問に対してAIの回答が1文字ずつストリーミング表示される。", loop:7000,
  css:`.q5 .ai{display:flex;gap:2.6cqw;align-items:flex-start}.q5 .ab{white-space:pre-wrap;min-height:12cqw}`,
  props:{ question:"集客に強いサイトってどう作る？", answer:"ポイントは3つです。\n①ターゲットを1人に絞る\n②結論をファーストビューに\n③問い合わせ導線を短く" },
  html:p=>`<div class="chat q5"><div class="bbl bR a pp" style="--d:.2s">${p.question}</div><div class="ai a fu" style="--d:.9s"><div class="avt bxa en">AI</div><div class="bbl bl ab" data-a>${DOTS}</div></div></div>`,
  init(el,p){ after(el,1800,()=>{ const a=el.querySelector("[data-a]"); a.textContent=""; typeText(a,p.answer,45,0); }); } },
{ id:82, pal:"clustr", name:"グループチャット", desc:"3人のアバターが順に発言し、会話が盛り上がっていく。", loop:5600,
  css:`.q6 .rw{display:flex;gap:2.4cqw;align-items:flex-end}.q6 .rw.me{flex-direction:row-reverse}.q6 .nm{font-size:2.8cqw;opacity:.7;margin:0 0 1cqw 1cqw}`,
  props:{ messages:[["A","あやか","新しいロゴできた？",0],["K","けんた","見たい！",0],["Y","わたし","いま送るね",1],["A","あやか","かわいい〜！",0]] },
  html:p=>`<div class="chat q6">${p.messages.map(([a,n,t,me])=>[a,n,t,me?1:0,me?'bxa':'bxs']).map(([a,n,t,me,c],i)=>`<div class="rw ${me?'me':''} a ${me?'sr':'sl'}" style="${D(.3,i,.6)}"><div class="avt ${c}">${a}</div><div>${me?'':`<div class="nm">${n}</div>`}<div class="bbl ${me?'bR':'bl'}">${t}</div></div></div>`).join("")}</div>` },
{ id:83, pal:"ibiza", name:"ハートが舞う", desc:"ライブ配信のように、ハートが下から次々とふわふわ浮かぶ。", loop:6000,
  css:`.q7 .ht{position:absolute;bottom:10cqw;width:var(--s);animation:q7 var(--t) ease-out var(--d) infinite;opacity:0}.q7 .ht path{fill:var(--c)}@keyframes q7{0%{opacity:0;transform:translate(0,0) scale(.4)}15%{opacity:1}100%{opacity:0;transform:translate(var(--x),-120cqw) scale(1)}}`,
  props:{ label:"LIVE 配信中" },
  html:p=>`<div class="center q7">${Array.from({length:16},(_,i)=>`<svg class="ht" viewBox="0 0 24 24" style="right:${8+(i*13)%22}cqw;--s:${7+(i%3)*2}cqw;--t:${2.6+(i%4)*.4}s;--d:${(i*.27).toFixed(2)}s;--x:${(i%2?-1:1)*(4+i%5*3)}cqw;--c:${i%3?'var(--acc)':'var(--sub)'}"><path d="M12 21s-7-4.5-9.5-9A5 5 0 0 1 12 6a5 5 0 0 1 9.5 6C19 16.5 12 21 12 21z"/></svg>`).join("")}<div class="h2 a fu" style="position:absolute;left:7cqw;bottom:14cqw">${p.label}</div></div>` },
{ id:84, pal:"cherry", name:"質問箱", desc:"質問カードがくるっと回って現れ、手書き風に回答が書かれる。", loop:5600,
  css:`.q8 .qb{width:80cqw;border-radius:5cqw;overflow:hidden}.q8 .qh{padding:2.6cqw;text-align:center}.q8 .qt{padding:7cqw 5cqw;text-align:center;background:var(--bg);color:var(--ink)}`,
  props:{ header:"質問箱", question:"未経験からWebデザイナーになれますか？", answer:"なれます。私もそうでした。" },
  html:p=>`<div class="center q8 fc" style="gap:6cqw"><div class="qb a fx" style="--d:.2s;--du:.8s"><div class="qh bxa sm">${p.header}</div><div class="qt h3">${p.question}</div></div><div class="h2 ac" data-a></div></div>`,
  init(el,p){ typeText(el.querySelector("[data-a]"),p.answer,90,1300); } },
{ id:85, pal:"mp213", name:"着信画面", desc:"電話の着信画面。アバターの周りに波紋が広がり、ボタンが揺れる。", loop:5000,
  css:`.q9 .ca{position:relative;width:32cqw;height:32cqw}.q9 .wv{position:absolute;inset:0;border-radius:50%;border:.8cqw solid var(--acc);animation:burst 1.8s ease-out infinite}.q9 .wv:nth-child(2){animation-delay:.6s}.q9 .wv:nth-child(3){animation-delay:1.2s}.q9 .av2{position:absolute;inset:0;border-radius:50%;display:grid;place-items:center;font-size:12cqw}.q9 .bt{width:17cqw;height:17cqw;border-radius:50%;display:grid;place-items:center;font-size:7cqw}.q9 .ok{animation:shake .6s ease 1s infinite}`,
  props:{ status:"着信中…", initial:"C", caller:"クライアント様" },
  html:p=>`<div class="center q9 fc" style="gap:8cqw"><div class="sm sb a fi">${p.status}</div><div class="ca"><i class="wv"></i><i class="wv"></i><i class="wv"></i><div class="av2 bxs en">${p.initial}</div></div><div class="h2 a fu" style="--d:.3s">${p.caller}</div><div class="fr" style="gap:22cqw"><div class="bt bxs">✕</div><div class="bt bxa ok">✆</div></div></div>` },
{ id:86, pal:"zanzibar", name:"通知スタック", desc:"通知カードが次々に上に積み重なり、件数バッジが増える。", loop:5600,
  css:`.q10 .sk{display:flex;flex-direction:column-reverse;gap:2.4cqw;width:84cqw}.q10 .nt{border-radius:4cqw;padding:3.6cqw 4cqw;display:flex;gap:3cqw;align-items:center}.q10 .bd{position:absolute;top:22cqw;right:12cqw;min-width:12cqw;height:12cqw;border-radius:9cqw;display:grid;place-items:center;font-size:5cqw}`,
  props:{ items:["予約が入りました","レビューが届きました","フォローされました","DMが届きました","予約が入りました"] },
  html:p=>`<div class="center q10"><div class="bd bxa en" data-n>0</div><div class="sk">${p.items.slice(0,5).map((t,i)=>`<div class="nt bxs a sd" style="${D(.3,i,.45)};--du:.45s"><div class="avt bxa" style="width:8cqw;height:8cqw;font-size:3.4cqw">${i+1}</div><span class="sm">${t}</span></div>`).join("")}</div></div>`,
  init(el,p){ const n=el.querySelector("[data-n]"), k=Math.min(5,p.items.length); every(el,450,i=>{ if(i<k){ n.textContent=i+1; n.animate([{transform:"scale(1.3)"},{transform:"none"}],{duration:250}); } },450); } },
{ id:87, pal:"madeira", name:"返信スレッド", desc:"投稿の下に返信が線でつながりながら追加されていく。", loop:5400,
  css:`.q11 .th{width:84cqw;position:relative;display:flex;flex-direction:column;gap:4cqw}.q11 .ln{position:absolute;left:5cqw;top:10cqw;bottom:6cqw;width:.6cqw;background:var(--surf);transform-origin:top;animation:growY 1.6s ease .6s both}.q11 .ps{display:flex;gap:3cqw;align-items:flex-start;position:relative}`,
  props:{ posts:[["Y","AIで作ったLP、公開しました！",1],["S","デザインきれい！何で作りました？",0],["Y","GetLayers + Claude です",1],["T","真似します笑",0]] },
  html:p=>`<div class="center q11"><div class="th"><div class="ln"></div>${p.posts.map(([a,t,me])=>[a,t,me?'bxa':'bxs']).map(([a,t,c],i)=>`<div class="ps a fu" style="${D(.3,i,.5)}"><div class="avt ${c}">${a}</div><div class="h3" style="font-size:4.4cqw;padding-top:2cqw">${t}</div></div>`).join("")}</div></div>` },
{ id:88, pal:"lemon", name:"対談吹き出し", desc:"左右の話者アイコンから大きな吹き出しが交互に飛び出す。", loop:6000,
  css:`.q12 .rw{display:flex;gap:3cqw;align-items:center}.q12 .rw.r{flex-direction:row-reverse}.q12 .avt{width:16cqw;height:16cqw;font-size:6cqw}.q12 .bbl{font-size:5cqw;max-width:60cqw}`,
  props:{ lines:[["先生","AIって何から始めればいい？",0],["生徒","まず毎日1回、話しかけてみて",1],["先生","それだけ？",0],["生徒","それだけ！",1]] },
  html:p=>`<div class="chat q12" style="gap:6cqw">${p.lines.map(([n,t,r],i)=>`<div class="rw ${r?'r':''}"><div class="avt ${r?'bxa':'bxs'} a pp" style="${D(.2,i,.7)}">${[...n][0]}</div><div class="bbl ${r?'bR':'bl'} a pp" style="${D(.35,i,.7)}">${t}</div></div>`).join("")}</div>` },
{ id:89, pal:"tanzania", name:"入力→送信", desc:"入力欄に文字が打たれ、送信ボタンで吹き出しが上へ飛ぶ。", loop:5600,
  css:`.q13 .ip{position:absolute;left:6cqw;right:6cqw;bottom:16cqw;display:flex;gap:2cqw;align-items:center;border-radius:9cqw;padding:2cqw 2cqw 2cqw 5cqw}.q13 .tx{flex:1;font-size:4cqw;font-weight:700;min-height:5cqw}.q13 .sd2{width:11cqw;height:11cqw;border-radius:50%;display:grid;place-items:center;font-size:5cqw}.q13 .sent{position:absolute;right:6cqw;bottom:34cqw;opacity:0}.q13 .go{animation:q13 .5s cubic-bezier(.2,.8,.2,1) forwards}@keyframes q13{from{opacity:0;transform:translateY(16cqw) scale(.6)}to{opacity:1;transform:none}}`,
  props:{ text:"見積もりお願いします！" },
  html:p=>`<div class="center q13"><div class="bbl bR sent">${p.text}</div><div class="ip bxs"><span class="tx" data-t></span><span class="sd2 bxa">➤</span></div></div>`,
  init(el,p){ typeText(el.querySelector("[data-t]"),p.text,90,500,()=>after(el,400,()=>{ el.querySelector("[data-t]").textContent=""; el.querySelector(".sent").classList.add("go"); el.querySelector(".sd2").animate([{transform:"scale(.8)"},{transform:"none"}],{duration:250}); })); } },
{ id:90, pal:"maldives", name:"口コミレビュー", desc:"星5つと口コミ本文、投稿者名が順に表示される。お客様の声に。", loop:5000,
  css:`.q14 .rv{width:84cqw;border-radius:5cqw;padding:6cqw;display:flex;flex-direction:column;gap:3cqw}.q14 .sr{color:var(--acc);font-size:6cqw;letter-spacing:.4cqw}.q14 .qm{font-size:16cqw;line-height:.6;color:var(--acc);font-family:Georgia,serif}`,
  props:{ review:"相談から公開まで2週間。予約が倍になりました。", author:"美容室オーナー 38歳" },
  html:p=>`<div class="center q14"><div class="rv bxs a fu" style="--d:.1s"><div class="sr">${ch("★★★★★","a zo",.4,.12)}</div><div class="qm a fi" style="--d:.9s">“</div><div class="h3 a fu" style="--d:1s">${p.review}</div><div class="sm a fu" style="--d:1.5s;opacity:.75">― ${p.author}</div></div></div>` },
]);
