/* タイトル・文字（#091〜#105）— 番号・名前・動きは変えない。新しいシーンは #151 から */
MOTION.add("タイトル・文字", [
 {id:91, name:"大事なこと（マスク立ち上がり）", pal:"clustr", loop:4200,
  desc:"ラベル→見出しが行ごとにマスクから立ち上がり、下線がスイープ。",
  props:{ label:"POINT 01", lines:["いちばん","大事な","こと。"], tag:"最後まで見てね" },
  html:p=>`<div class="center s-title">
    <div class="lab">${p.label}</div>
    <div>${p.lines.slice(0,3).map(l=>`<div class="line"><span>${l}</span></div>`).join("")}</div>
    <div class="ul"></div>
    <div class="tag2">${p.tag}</div></div>`},
{ id:92, pal:"clustr", name:"1文字ずつポップ", desc:"見出しの文字が1文字ずつ弾むように飛び出す。", loop:4000,
  props:{ line1:"今日から", line2:"AI時代", sub:"はじめての人のための講座" },
  html:p=>`<div class="center fc" style="gap:4cqw"><div class="h1" style="font-size:13cqw">${ch(p.line1,"a bo",.2,.08)}</div><div class="h1 ac" style="font-size:13cqw">${ch(p.line2,"a bo",.6,.08)}</div><div class="sm sb a fu" style="--d:1.3s">${p.sub}</div></div>` },
{ id:93, pal:"ibiza", name:"タイプライター見出し", desc:"カーソルが点滅しながら見出しがタイプされる。", loop:5200,
  props:{ label:"CHAPTER 02", text:"迷ったら、まず作る。" },
  html:p=>`<div class="center fc" style="gap:4cqw;align-items:flex-start;padding:0 9cqw"><span class="sm ac en a fi">${p.label}</span><div class="h1" style="font-size:12cqw"><span data-t></span><span class="cu" style="height:11cqw;width:1.4cqw"></span></div></div>`,
  init(el,p){ typeText(el.querySelector("[data-t]"),p.text,110,500); } },
{ id:94, pal:"cherry", name:"マーカーハイライト", desc:"キーワードの下に蛍光マーカーが左から引かれる。", loop:4400,
  css:`.w3 .mk{background:linear-gradient(transparent 58%,color-mix(in srgb,var(--acc) 55%,transparent) 58%) no-repeat;background-size:0 100%;animation:w3 .8s cubic-bezier(.6,0,.2,1) 1s forwards;padding:0 1cqw}@keyframes w3{to{background-size:100% 100%}}`,
  props:{ before:"集客で大切なのは", keyword:"続けること", after:"です。" },
  html:p=>`<div class="center w3 fc" style="gap:2cqw"><div class="h2 a fu" style="--d:.2s">${p.before}</div><div class="h1 a fu" style="--d:.5s;font-size:13cqw"><span class="mk">${p.keyword}</span></div><div class="h2 a fu" style="--d:.7s">${p.after}</div></div>` },
{ id:95, pal:"mp213", name:"縦書きタイトル", desc:"縦書きの見出しが上から下へ1文字ずつ現れる。和風・エモい演出に。", loop:4600,
  css:`.w4 .vt{writing-mode:vertical-rl;font-weight:900;font-size:13cqw;letter-spacing:.2em;line-height:1.5}.w4 .bar2{width:.6cqw;height:50cqw;background:var(--acc);transform-origin:top;animation:growY 1s ease .2s both}`,
  props:{ sub:"前橋のちいさな制作室", line1:"ことばを", line2:"かたちに" },
  html:p=>`<div class="center w4 fr" style="flex-direction:row;justify-content:center;gap:6cqw"><div class="vt sm sb" style="font-size:4.4cqw;letter-spacing:.3em">${ch(p.sub,"a fi",.8,.05)}</div><div class="bar2"></div><div class="vt">${ch(p.line1,"a sd",.3,.1)}</div><div class="vt ac">${ch(p.line2,"a sd",.8,.1)}</div></div>` },
{ id:96, pal:"zanzibar", name:"ブラーからズーム", desc:"ぼやけた大きな文字がピントを合わせながら縮んで定位置へ。", loop:4000,
  props:{ line1:"本気の", line2:"LP", sub:"3日で作ります" },
  html:p=>`<div class="center fc" style="gap:4cqw"><div class="h1 a bi" style="--d:.2s;--du:1s;font-size:16cqw">${p.line1}</div><div class="h1 ac a bi" style="--d:.5s;--du:1s;font-size:16cqw">${p.line2}</div><div class="h3 a fu" style="--d:1.4s">${p.sub}</div></div>` },
{ id:97, pal:"madeira", name:"グリッチ文字", desc:"文字が色ずれしながらノイズのように乱れ、パッと定着する。", loop:4400,
  css:`.w6 .gt{position:relative;font-weight:900;font-size:16cqw;font-family:Inter,sans-serif}.w6 .gt:before,.w6 .gt:after{content:attr(data-t);position:absolute;inset:0;animation:w6 .9s steps(2) .3s 2}.w6 .gt:before{color:var(--acc);clip-path:inset(0 0 55% 0)}.w6 .gt:after{color:var(--sub);clip-path:inset(55% 0 0 0)}@keyframes w6{0%{transform:translate(0)}20%{transform:translate(-3cqw,1cqw)}40%{transform:translate(3cqw,-1cqw)}60%{transform:translate(-2cqw,0)}80%{transform:translate(2cqw,1cqw)}100%{transform:translate(0);opacity:0}}`,
  props:{ word:"ERROR", before:"そのサイト、", accent:"古く", after:"なってない？" },
  html:p=>`<div class="center w6 fc" style="gap:4cqw"><div class="gt" data-t="${p.word}">${p.word}</div><div class="h3 a fu" style="--d:2s">${p.before}<span class="ac">${p.accent}</span>${p.after}</div></div>` },
{ id:98, pal:"lemon", name:"帯つきスライド", desc:"背景の帯が伸びたあと、その上を文字がスライドして乗る。", loop:4400,
  css:`.w7 .bd{display:inline-block;padding:2cqw 4cqw;position:relative;overflow:hidden}.w7 .bd:before{content:"";position:absolute;inset:0;background:var(--acc);transform-origin:left;animation:growX .5s cubic-bezier(.7,0,.2,1) var(--d) both}.w7 .bd span{position:relative;color:var(--onAcc);display:inline-block;animation:slideUp .5s ease calc(var(--d) + .35s) both}`,
  props:{ lines:["個人事業主の","ための","ホームページ"] },
  html:p=>`<div class="center w7 fc" style="gap:3cqw;align-items:flex-start;padding-left:9cqw">${p.lines.map((t,i)=>`<div class="bd h1" style="font-size:10cqw;--d:${.2+i*.35}s"><span>${t}</span></div>`).join("")}</div>` },
{ id:99, pal:"tanzania", name:"単語入れ替え", desc:"後半の単語だけが次々と縦に入れ替わる。キャッチコピーの言い換えに。", loop:6000,
  css:`.w8 .sl2{height:15cqw;overflow:hidden;position:relative}.w8 .rl{animation:w8 4.8s cubic-bezier(.7,0,.2,1) .4s both}.w8 .rl div{height:15cqw;line-height:15cqw}@keyframes w8{0%,20%{transform:translateY(0)}30%,50%{transform:translateY(-15cqw)}60%,80%{transform:translateY(-30cqw)}90%,100%{transform:translateY(-45cqw)}}`,
  props:{ lead:"AIで作るサイトは", words:["速い。","安い。","きれい。","最強。"] },
  html:p=>`<div class="center w8 fc" style="gap:4cqw"><div class="h2 a fu">${p.lead}</div><div class="sl2 h1 ac" style="font-size:13cqw"><div class="rl">${p.words.slice(0,4).map(w=>`<div>${w}</div>`).join("")}</div></div></div>` },
{ id:100, pal:"maldives", name:"アウトラインから塗り", desc:"輪郭だけの文字が下から色で満たされていく。", loop:4400,
  css:`.w9 .ot{font-family:Inter,sans-serif;font-weight:800;font-size:22cqw;line-height:1;color:transparent;-webkit-text-stroke:.5cqw var(--ink);position:relative}.w9 .ot:after{content:attr(data-t);position:absolute;inset:0;color:var(--acc);-webkit-text-stroke:0;clip-path:inset(100% 0 0 0);animation:w9 1.4s cubic-bezier(.6,0,.2,1) .6s forwards}@keyframes w9{to{clip-path:inset(0 0 0 0)}}`,
  props:{ word1:"FULL", word2:"POWER", sub:"全力でサポートします" },
  html:p=>`<div class="center w9 fc" style="gap:4cqw"><div class="ot a fi" data-t="${p.word1}">${p.word1}</div><div class="ot a fi" data-t="${p.word2}" style="--d:.2s">${p.word2}</div><div class="h3 a fu" style="--d:1.8s">${p.sub}</div></div>` },
{ id:101, pal:"glowup", name:"ローワーサード", desc:"画面下に名前と肩書きのテロップが2段でスライドイン。インタビュー動画に。", loop:4600,
  css:`.w10 .lt{position:absolute;left:6cqw;bottom:22cqw;display:flex;flex-direction:column;align-items:flex-start;gap:1cqw}.w10 .n1{padding:2.4cqw 5cqw;font-size:7cqw}.w10 .n2{padding:1.6cqw 5cqw;font-size:3.8cqw}.w10 .ph{position:absolute;inset:14cqw 10cqw 60cqw;border-radius:4cqw;border:.5cqw dashed var(--sub);display:grid;place-items:center;opacity:.6}`,
  props:{ name:"やまだ はなこ", role:"FUN WEB DESIGN 代表", placeholder:"人物映像エリア" },
  html:p=>`<div class="center w10"><div class="ph sm sb">${p.placeholder}</div><div class="lt"><div class="n1 bxa h2 a sl" style="--d:.3s">${p.name}</div><div class="n2 bxs sm a sl" style="--d:.55s">${p.role}</div></div></div>` },
{ id:102, pal:"clustr", name:"「3つの理由」見出し", desc:"大きな数字がスピンして現れ、見出しが続く。リスト動画の導入に。", loop:4200,
  props:{ lead:"選ばれる", number:"3", title:"つの<br>理由" },
  html:p=>`<div class="center fc" style="gap:2cqw"><div class="h3 sb a fu">${p.lead}</div><div class="fr" style="gap:2cqw"><span class="en ac a sp" style="font-size:40cqw;line-height:1;--d:.3s;--du:.8s">${p.number}</span><span class="h1 a sr" style="--d:.9s;font-size:12cqw">${p.title}</span></div></div>` },
{ id:103, pal:"ibiza", name:"引用フレーズ", desc:"大きな引用符が開いて、名言がフェードイン。", loop:4600,
  css:`.w12 .qm{font-family:Georgia,serif;font-size:40cqw;line-height:.5;color:var(--acc)}`,
  props:{ quote:"完璧を目指すより、<br>まず終わらせろ。", source:"仕事が速い人の口ぐせ" },
  html:p=>`<div class="center w12 fc" style="gap:3cqw;padding:0 10cqw;align-items:flex-start"><div class="qm a zo" style="--d:.1s">“</div><div class="h2 a fu" style="--d:.6s;font-size:8cqw">${p.quote}</div><div class="sm sb a fu" style="--d:1.2s">― ${p.source}</div></div>` },
{ id:104, pal:"cherry", name:"取り消し線で言い換え", desc:"最初の言葉に線が引かれ、下から本当に言いたい言葉が出る。", loop:4600,
  css:`.w13 .ol{position:relative;opacity:.55}.w13 .ol:after{content:"";position:absolute;left:-2cqw;right:-2cqw;top:52%;height:1.4cqw;background:var(--acc);transform-origin:left;animation:growX .4s ease 1s both}`,
  props:{ lead:"ホームページは", before:"名刺代わり", after:"営業マン", tail:"です。" },
  html:p=>`<div class="center w13 fc" style="gap:4cqw"><div class="h2">${p.lead}</div><div class="h1 ol a fi" style="--d:.2s;font-size:12cqw">${p.before}</div><div class="h1 ac a bo" style="--d:1.5s;font-size:12cqw">${p.after}</div><div class="h2 a fu" style="--d:1.9s">${p.tail}</div></div>` },
{ id:105, pal:"mp213", name:"スタンプ「決定！」", desc:"判子が上から押されるように回転しながら着地する。", loop:4000,
  css:`.w14 .stp{width:56cqw;height:56cqw;border-radius:50%;border:2cqw solid var(--acc);color:var(--acc);display:grid;place-items:center;font-weight:900;font-size:15cqw;animation:w14 .45s cubic-bezier(.3,1.4,.5,1) .5s both}@keyframes w14{from{opacity:0;transform:scale(2.4) rotate(-30deg)}to{opacity:1;transform:rotate(-12deg)}}`,
  props:{ label:"今月のおすすめプラン", stamp:"決定", title:"LP制作パック" },
  html:p=>`<div class="center w14 fc" style="gap:6cqw"><div class="h3 a fu">${p.label}</div><div class="stp">${p.stamp}</div><div class="h2 a fu" style="--d:1.1s">${p.title}</div></div>` },
]);
