/* ロゴ（#106〜#120）— 番号・名前・動きは変えない。新しいシーンは #151 から */
MOTION.add("ロゴ", [
 {id:106, name:"ロゴ・リビール", pal:"ibiza", loop:4200,
  desc:"同心円のマークが順に広がり、ワードマークが1文字ずつ立ち上がる。",
  html:`<div class="center s-logo">
    <div class="mark"><i></i><i></i><i></i></div>
    <div class="word">${[..."FUNWEB"].map((c,i)=>`<span style="--d:${.8+i*.07}s">${c}</span>`).join("")}</div>
    <div class="tagl">DESIGN STUDIO</div></div>`},
{ id:107, pal:"madeira", name:"線画で描かれるロゴ", desc:"ロゴマークの輪郭が線で描かれ、最後に塗りが入る。", loop:4600,
  css:`.o1 svg{width:42cqw}.o1 .fill{animation:fadeIn .5s ease 1.5s both}`,
  html:`<div class="center o1 fc" style="gap:6cqw"><svg viewBox="0 0 50 50"><path class="fill" d="M25 4L45 15V35L25 46L5 35V15Z" fill="var(--acc)"/><path d="M25 4L45 15V35L25 46L5 35V15Z" fill="none" stroke="var(--ink)" stroke-width="1.6" pathLength="100" class="dw" style="--du:1.3s"/><path d="M17 20h16M17 27h11M17 34h16" stroke="var(--onAcc)" stroke-width="2.4" stroke-linecap="round" class="a fi" style="--d:1.8s"/></svg><div class="h2 en a fu" style="--d:1.9s;letter-spacing:.2em">HEXA LAB</div></div>` },
{ id:108, pal:"lemon", name:"ロゴフリップ", desc:"ロゴが縦にくるっと回転して表を向き、社名が続く。", loop:4200,
  css:`.o2 .mk{width:36cqw;height:36cqw;border-radius:9cqw;display:grid;place-items:center;font-size:18cqw;animation:o2 1s cubic-bezier(.3,1.2,.5,1) .2s both}@keyframes o2{from{transform:perspective(200cqw) rotateY(-540deg) scale(.4);opacity:0}to{transform:none;opacity:1}}`,
  html:`<div class="center o2 fc" style="gap:6cqw"><div class="mk bxa en">F</div><div class="h2 a fu" style="--d:1.1s">FUN WEB DESIGN</div></div>` },
{ id:109, pal:"tanzania", name:"シェイプ集合", desc:"四方から4つの図形が集まって1つのロゴマークになる。", loop:4400,
  css:`.o3 .gd{display:grid;grid-template-columns:repeat(2,16cqw);gap:2cqw}.o3 .gd i{height:16cqw;animation:o3 .8s cubic-bezier(.3,1.3,.5,1) var(--d) both}@keyframes o3{from{transform:translate(var(--x),var(--y)) rotate(180deg);opacity:0}}`,
  html:`<div class="center o3 fc" style="gap:7cqw"><div class="gd">${[['-40cqw','-40cqw','50% 0 50% 50%','var(--acc)'],['40cqw','-40cqw','50%','var(--sub)'],['-40cqw','40cqw','2cqw','var(--sub)'],['40cqw','40cqw','50% 50% 50% 0','var(--acc)']].map(([x,y,r,c],i)=>`<i style="--x:${x};--y:${y};--d:${.2+i*.1}s;border-radius:${r};background:${c}"></i>`).join("")}</div><div class="h2 en a fu" style="--d:1.1s;letter-spacing:.15em">QUAD</div></div>` },
{ id:110, pal:"maldives", name:"ワイプリビール", desc:"アクセント色のバーが横切ると、その後ろからロゴが現れる。", loop:4200,
  css:`.o4 .wp{position:relative;overflow:hidden;padding:2cqw 4cqw}.o4 .wp:after{content:"";position:absolute;inset:0;background:var(--acc);animation:o4 1s cubic-bezier(.7,0,.2,1) .2s both}@keyframes o4{0%{transform:translateX(-101%)}50%{transform:none}100%{transform:translateX(101%)}}.o4 .tx{animation:fadeIn .01s linear .7s both}`,
  html:`<div class="center o4 fc" style="gap:3cqw"><div class="wp"><div class="tx en" style="font-size:14cqw">NORTH</div></div><div class="wp" style="--d:.2s"><div class="tx sm sb" style="letter-spacing:.5em">CREATIVE STUDIO</div></div></div>` },
{ id:111, pal:"glowup", name:"シャイン（光沢）", desc:"ロゴの上を斜めの光がすっと走り、高級感を出す。", loop:3800,
  css:`.o5 .lg{position:relative;overflow:hidden;padding:5cqw 8cqw;border-radius:5cqw}.o5 .lg:after{content:"";position:absolute;top:-50%;bottom:-50%;width:16cqw;background:linear-gradient(90deg,transparent,rgba(255,255,255,.65),transparent);transform:rotate(20deg) translateX(-60cqw);animation:o5 1.2s ease 1s both}@keyframes o5{to{transform:rotate(20deg) translateX(90cqw)}}`,
  html:`<div class="center o5 fc" style="gap:5cqw"><div class="lg bxa a zo"><span class="en" style="font-size:12cqw">LUXE</span></div><div class="sm sb a fu" style="--d:.5s;letter-spacing:.4em">HAIR SALON</div></div>` },
{ id:112, pal:"clustr", name:"タグライン入力", desc:"ロゴの下でキャッチコピーがタイプされる。", loop:5000,
  html:`<div class="center fc" style="gap:4cqw"><div class="fr a pp" style="gap:3cqw"><div class="avt bxa en" style="width:16cqw;height:16cqw;font-size:8cqw;border-radius:4cqw">Y</div><div class="h2 en">YOUR BRAND</div></div><div class="sm sb mono"><span data-t></span><span class="cu" style="height:3.6cqw"></span></div></div>`,
  init(el){ typeText(el.querySelector("[data-t]"),"AIで、つくるをもっと速く。",90,900); } },
{ id:113, pal:"ibiza", name:"パーティクル集合", desc:"散らばった粒が中心に吸い寄せられてロゴの円になる。", loop:4600,
  css:`.o7 .pc{position:relative;width:40cqw;height:40cqw}.o7 .pc i{position:absolute;left:50%;top:50%;width:3cqw;height:3cqw;margin:-1.5cqw;border-radius:50%;background:var(--acc);animation:o7 1.2s cubic-bezier(.6,0,.2,1) var(--d) both}@keyframes o7{from{transform:translate(var(--fx),var(--fy));opacity:0}30%{opacity:1}to{transform:translate(var(--tx),var(--ty))}}`,
  html:`<div class="center o7 fc" style="gap:6cqw"><div class="pc">${Array.from({length:24},(_,i)=>{const a=i/24*Math.PI*2;return `<i style="--tx:${(Math.cos(a)*18).toFixed(1)}cqw;--ty:${(Math.sin(a)*18).toFixed(1)}cqw;--fx:${(Math.cos(a*3)*60).toFixed(1)}cqw;--fy:${(Math.sin(a*5)*80).toFixed(1)}cqw;--d:${(i%6*.05).toFixed(2)}s"></i>`}).join("")}<div class="en a zo" style="position:absolute;inset:0;display:grid;place-items:center;font-size:12cqw;--d:1.2s">O</div></div><div class="h2 en a fu" style="--d:1.4s;letter-spacing:.2em">ORBIT</div></div>` },
{ id:114, pal:"cherry", name:"バウンド着地", desc:"ロゴが上から落ちてきて弾み、影が伸び縮みする。", loop:4000,
  css:`.o8 .lg{width:34cqw;height:34cqw;border-radius:50%;display:grid;place-items:center;font-size:14cqw;animation:o8 1.1s ease .2s both}@keyframes o8{0%{transform:translateY(-90cqw)}45%{transform:none;animation-timing-function:ease-out}62%{transform:translateY(-14cqw);animation-timing-function:ease-in}78%{transform:none}88%{transform:translateY(-4cqw)}100%{transform:none}}.o8 .sh{width:30cqw;height:3cqw;border-radius:50%;background:var(--ink);opacity:.18;margin-top:3cqw;animation:o8s 1.1s ease .2s both}@keyframes o8s{0%{transform:scaleX(.2)}45%{transform:none}62%{transform:scaleX(.6)}78%,100%{transform:none}}`,
  html:`<div class="center o8 fc"><div class="lg bxa en">b</div><div class="sh"></div><div class="h2 a fu" style="--d:1.3s;margin-top:5cqw">bounce kids</div></div>` },
{ id:115, pal:"mp213", name:"上下分割スライド", desc:"ロゴが上下2つに割れた状態から、左右逆方向にスライドして合体。", loop:4200,
  css:`.o9 .sp2{position:relative;font-family:Inter,sans-serif;font-weight:800;font-size:20cqw;line-height:1}.o9 .hf{display:block;animation:o9 .9s cubic-bezier(.7,0,.2,1) .3s both}.o9 .t{clip-path:inset(0 0 50% 0);--x:-60cqw}.o9 .b{position:absolute;inset:0;clip-path:inset(50% 0 0 0);--x:60cqw;color:var(--acc)}@keyframes o9{from{transform:translateX(var(--x))}}`,
  html:`<div class="center o9 fc" style="gap:5cqw"><div class="sp2"><span class="hf t">SPLIT</span><span class="hf b">SPLIT</span></div><div class="sm sb a fu" style="--d:1.2s;letter-spacing:.4em">DESIGN OFFICE</div></div>` },
{ id:116, pal:"zanzibar", name:"ロゴグリッド（取引先）", desc:"取引先ロゴの枠がタイル状に順に並ぶ。実績紹介に。", loop:4600,
  css:`.o10 .gd{display:grid;grid-template-columns:repeat(3,25cqw);gap:2.4cqw}.o10 .gd span{height:16cqw;border-radius:3cqw;display:grid;place-items:center;font-family:Inter,sans-serif;font-weight:800;font-size:3.6cqw;letter-spacing:.1em}`,
  html:`<div class="center o10 fc" style="gap:6cqw"><div class="h2 a fu">導入実績</div><div class="gd">${['ACME','NOVA','KAI','MORI','LUMA','SORA','HANA','TERA','YUZU'].map((t,i)=>`<span class="${i==4?'bxa':'bxs'} a pp" style="--d:${(.3+((i*4)%9)*.08).toFixed(2)}s">${t}</span>`).join("")}</div><div class="sm sb a fu" style="--d:1.2s">ほか 120 社以上</div></div>` },
{ id:117, pal:"madeira", name:"モノグラム", desc:"頭文字が筆記のように描かれ、円で囲まれる。", loop:4600,
  css:`.o11 svg{width:52cqw}`,
  html:`<div class="center o11 fc" style="gap:5cqw"><svg viewBox="0 0 60 60"><circle cx="30" cy="30" r="27" fill="none" stroke="var(--acc)" stroke-width="1.4" pathLength="100" class="dw" style="--d:1.2s;--du:1s"/><path d="M18 18L30 32L42 18M30 32V44" fill="none" stroke="var(--ink)" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" pathLength="100" class="dw" style="--d:.2s;--du:1s"/></svg><div class="h3 a fu" style="--d:2s;letter-spacing:.3em">YOUR BRAND</div></div>` },
{ id:118, pal:"lemon", name:"ズームアウト＆パターン", desc:"ロゴが大きく映ったあと引いていき、背景に同じマークが敷き詰められる。", loop:4600,
  css:`.o12 .pt{position:absolute;inset:-10cqw;display:grid;grid-template-columns:repeat(6,1fr);gap:4cqw;opacity:0;animation:o12f .6s ease 1.2s forwards}@keyframes o12f{to{opacity:.4}}.o12 .pt i{aspect-ratio:1;border-radius:50%;border:1cqw solid var(--surf)}.o12 .lg{position:relative;width:34cqw;height:34cqw;border-radius:50%;display:grid;place-items:center;font-size:14cqw;animation:o12 1.2s cubic-bezier(.6,0,.2,1) .1s both}@keyframes o12{from{transform:scale(5)}}`,
  html:`<div class="center o12"><div class="pt">${'<i></i>'.repeat(66)}</div><div class="lg bxa en">o</div></div>` },
{ id:119, pal:"tanzania", name:"エンドカード", desc:"ロゴ・アカウント名・フォローボタンが順に出る、動画の締めくくり。", loop:5000,
  css:`.o13 .fb{padding:3cqw 9cqw;border-radius:9cqw;font-size:4.6cqw}.o13 .fb.on{animation:pulse 1s ease 1.8s infinite}`,
  html:`<div class="center o13 fc" style="gap:4cqw"><div class="avt bxa en a zo" style="width:26cqw;height:26cqw;font-size:11cqw">F</div><div class="h2 a fu" style="--d:.5s">@funwebdesign</div><div class="sm sb a fu" style="--d:.7s">AI × Webデザインを毎日発信</div><div class="fb bxa h3 on a pp" style="--d:1.1s">フォローする</div></div>` },
{ id:120, pal:"maldives", name:"アプリアイコン", desc:"角丸のアプリアイコンがポンと出て、アプリ名とダウンロード表示。", loop:4400,
  css:`.o14 .ic{width:40cqw;height:40cqw;border-radius:10cqw;display:grid;place-items:center;box-shadow:0 4cqw 10cqw rgba(0,0,0,.25)}.o14 .ic svg{width:20cqw}`,
  html:`<div class="center o14 fc" style="gap:5cqw"><div class="ic bxa a bo" style="--d:.2s"><svg viewBox="0 0 24 24" fill="none" stroke="var(--onAcc)" stroke-width="2.4" stroke-linecap="round"><path d="M5 12l4 4 10-10"/></svg></div><div class="h2 a fu" style="--d:.7s">Todo Flow</div><div class="fr sm" style="gap:2cqw"><span class="ac a fi" style="--d:1s">★ 4.9</span><span class="sb a fi" style="--d:1.1s">・ 10万DL</span></div></div>` },
]);
