/* フック・冒頭（#136〜#150）— 番号・名前・動きは変えない。新しいシーンは #151 から */
MOTION.add("フック・冒頭", [
 {id:136, name:"!? パンチイン", pal:"madeira", loop:4000,
  desc:"巨大な「!?」がズームインして揺れ、衝撃波リング→キャッチコピー。冒頭2秒の掴みに。",
  props:{ mark:"!?", before:"知らないと", accent:"損", sub:"9割の人がやってる失敗" },
  html:p=>`<div class="center s-hook"><div class="ring"></div><div class="q">${p.mark}</div>
    <div class="l1">${p.before}<b>${p.accent}</b></div><div class="l2">${p.sub}</div></div>`},
{ id:137, pal:"madeira", name:"「待って！」ストップ", desc:"八角形のストップサインが勢いよく出て震え、「待って！」と止める。", loop:4000,
  css:`.hk1 .sg{width:56cqw;height:56cqw;clip-path:polygon(30% 0,70% 0,100% 30%,100% 70%,70% 100%,30% 100%,0 70%,0 30%);display:grid;place-items:center;font-size:13cqw;animation:punch .4s cubic-bezier(.2,.9,.2,1) .2s both,shake .5s ease .6s}`,
  props:{ sign:"待って", text:"その投稿、<br>出す前に見て" },
  html:p=>`<div class="center hk1 fc" style="gap:6cqw"><div class="sg bxa h1">${p.sign}</div><div class="h2 a fu" style="--d:1s">${p.text}</div></div>` },
{ id:138, pal:"lemon", name:"カウントダウン3-2-1", desc:"3・2・1の数字が拡大しながら切り替わり、最後にGO。", loop:4600,
  css:`.hk2 .n{position:absolute;font-family:Inter,sans-serif;font-weight:800;font-size:48cqw;opacity:0;animation:hk2 .9s ease var(--d) both}@keyframes hk2{0%{opacity:0;transform:scale(2)}20%{opacity:1;transform:scale(1)}80%{opacity:1}100%{opacity:0;transform:scale(.6)}}.hk2 .go{animation:punch .4s ease 2.9s both}`,
  props:{ go:"GO!" },
  html:p=>`<div class="center hk2">${[3,2,1].map((n,i)=>`<span class="n ${i==2?'ac':''}" style="--d:${.1+i*.9}s">${n}</span>`).join("")}<span class="go h1 ac" style="font-size:22cqw;opacity:0">${p.go}</span></div>` },
{ id:139, pal:"tanzania", name:"保存推奨", desc:"ブックマークアイコンが落ちてきて「保存して見返してね」と促す。", loop:4200,
  css:`.hk3 svg{width:28cqw;fill:var(--acc)}.hk3 .tg2{padding:2cqw 6cqw;border-radius:9cqw}`,
  props:{ title:"保存推奨", tag:"あとで見返せるように" },
  html:p=>`<div class="center hk3 fc" style="gap:5cqw"><div class="a dp" style="--d:.2s"><svg viewBox="0 0 24 24"><path d="M6 2h12v20l-6-5-6 5z"/></svg></div><div class="h1 a fu" style="--d:.7s;font-size:13cqw">${p.title}</div><div class="tg2 bxs sm a pp" style="--d:1s">${p.tag}</div></div>` },
{ id:140, pal:"maldives", name:"「知ってた？」", desc:"巨大な？マークが揺れ、問いかけのテロップがスライドイン。", loop:4400,
  css:`.hk4 .qm{font-family:Inter,sans-serif;font-weight:800;font-size:60cqw;line-height:1;color:var(--acc);opacity:.9;animation:spinIn .7s cubic-bezier(.3,1.3,.5,1) .1s both,floatY 2s ease-in-out 1s infinite}`,
  props:{ question:"知ってた？", before:"サイトは", accent:"3秒", after:"で判断される" },
  html:p=>`<div class="center hk4 fc"><div class="qm">?</div><div class="h2 a sl" style="--d:.7s">${p.question}</div><div class="h3 a sr" style="--d:.9s">${p.before}<span class="ac">${p.accent}</span>${p.after}</div></div>` },
{ id:141, pal:"glowup", name:"「最後まで見て」", desc:"下向き矢印が跳ね続け、最後まで見るよう促す。", loop:6000,
  css:`.hk5 svg{width:18cqw;color:var(--acc);animation:i4 1s ease-in-out infinite}`,
  props:{ before:"最後に", accent:"プレゼント", after:"あり", sub:"最後まで見てね" },
  html:p=>`<div class="center hk5 fc" style="gap:5cqw"><div class="h1 a fu" style="font-size:11cqw;text-align:center">${p.before}<br><span class="ac">${p.accent}</span>${p.after}</div><div class="h3 a fu" style="--d:.4s">${p.sub}</div><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M6 9l6 6 6-6"/></svg></div>` },
{ id:142, pal:"clustr", name:"衝撃の数字", desc:"大きな数字がズームで迫り、画面全体が一瞬揺れる。", loop:4200,
  css:`.hk6 .big{font-family:Inter,sans-serif;font-weight:800;font-size:44cqw;line-height:1;color:var(--acc);animation:punch .45s cubic-bezier(.2,.9,.2,1) .2s both}.hk6{animation:shake .4s ease .6s}`,
  props:{ value:"97", unit:"%", text:"の人が<br>ここで離脱します" },
  html:p=>`<div class="center hk6 fc" style="gap:2cqw"><div class="big">${p.value}<small style="font-size:16cqw">${p.unit}</small></div><div class="h2 a fu" style="--d:.9s;text-align:center">${p.text}</div></div>` },
{ id:143, pal:"ibiza", name:"NG例スタンプ", desc:"サンプル画面の上に大きな×と「NG」の判子が押される。", loop:4400,
  css:`.hk7 .mock{width:66cqw;height:86cqw;border-radius:4cqw;padding:5cqw;display:flex;flex-direction:column;gap:3cqw}.hk7 .mock i{display:block;height:4cqw;border-radius:1cqw;background:currentColor;opacity:.4}.hk7 .xx{position:absolute;inset:0;display:grid;place-items:center}.hk7 .xx svg{width:70cqw;color:#E5484D}.hk7 .ng{position:absolute;bottom:30cqw;right:12cqw;padding:2cqw 5cqw;border:1.4cqw solid #E5484D;color:#E5484D;font-weight:900;font-size:10cqw;border-radius:3cqw;animation:w14 .4s cubic-bezier(.3,1.4,.5,1) 1.4s both}`,
  props:{ stamp:"NG" },
  html:p=>`<div class="center hk7"><div class="mock bxs a fi">${[90,60,100,100,80,100,40,100,70].map(w=>`<i style="width:${w}%"></i>`).join("")}</div><div class="xx"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round"><path d="M5 5l14 14" pathLength="100" class="dw" style="--d:.6s;--du:.3s"/><path d="M19 5L5 19" pathLength="100" class="dw" style="--d:.9s;--du:.3s"/></svg></div><div class="ng">${p.stamp}</div></div>` },
{ id:144, pal:"cherry", name:"「こんな人へ」", desc:"「こんな人は見て」に続いて、当てはまる人のリストがチェックされる。", loop:5200,
  css:`.hk8 .it{display:flex;gap:3cqw;align-items:center;width:78cqw}.hk8 .bx2{width:7cqw;height:7cqw;border-radius:1.6cqw;display:grid;place-items:center;font-size:4.4cqw;flex:none}`,
  props:{ before:"こんな人は", accent:"見て", items:["ホームページが古い","集客をSNSだけに頼っている","AIを使いこなせていない"] },
  html:p=>`<div class="center hk8 fc" style="gap:4cqw"><div class="h1 a zi" style="font-size:12cqw">${p.before}<span class="ac">${p.accent}</span></div>${p.items.map((t,i)=>`<div class="it a sl" style="${D(.8,i,.4)}"><span class="bx2 bxa a pp" style="${D(1,i,.4)}">✓</span><span class="h3">${t}</span></div>`).join("")}</div>` },
{ id:145, pal:"mp213", name:"カーテンで結論", desc:"左右のカーテンが開いて、中央に結論が現れる。", loop:4400,
  css:`.hk9 .cu2{position:absolute;top:0;bottom:0;width:51%;background:var(--surf);animation:hk9 .9s cubic-bezier(.7,0,.2,1) .8s both}.hk9 .l{left:0;--x:-100%}.hk9 .r{right:0;--x:100%}@keyframes hk9{to{transform:translateX(var(--x))}}.hk9 .lb3{position:absolute;top:30cqw;left:0;right:0;text-align:center;z-index:2;color:var(--onSurf);animation:hk9f .3s ease .7s both}@keyframes hk9f{to{opacity:0}}`,
  props:{ label:"結論", conclusion:"外注より<br>AIが速い", teaser:"結論から言うと…" },
  html:p=>`<div class="center hk9 fc" style="gap:3cqw"><div class="sm sb">${p.label}</div><div class="h1 ac" style="font-size:13cqw">${p.conclusion}</div><div class="cu2 l"></div><div class="cu2 r"></div><div class="lb3 h2">${p.teaser}</div></div>` },
{ id:146, pal:"zanzibar", name:"ランキング発表", desc:"スポットライトが揺れて照らし、「第1位」がドラムロール後に登場。", loop:5000,
  css:`.hk10{overflow:hidden}.hk10 .sp3{position:absolute;width:70cqw;height:70cqw;border-radius:50%;background:radial-gradient(circle,color-mix(in srgb,var(--acc) 45%,transparent),transparent 65%);animation:hk10 1.6s ease-in-out both}@keyframes hk10{0%{transform:translate(-30cqw,-20cqw)}35%{transform:translate(25cqw,10cqw)}70%{transform:translate(-15cqw,25cqw)}100%{transform:none}}`,
  props:{ drumroll:"ドゥルルルル…", rank:"1", winner:"STUDIO" },
  html:p=>`<div class="center hk10 fc" style="gap:3cqw"><div class="sp3"></div><div class="h3 a fi" style="--d:.1s;position:relative">${p.drumroll}</div><div class="h1 a punch" style="--an:punch;--d:1.6s;position:relative;font-size:15cqw">第<span class="ac">${p.rank}</span>位</div><div class="h2 a fu" style="--d:2s;position:relative">${p.winner}</div></div>` },
{ id:147, pal:"madeira", name:"警告テープ", desc:"斜めのストライプ帯が左右から流れ込み、注意喚起の文字が出る。", loop:5000,
  css:`.hk11 .tp{position:absolute;left:-20cqw;right:-20cqw;height:14cqw;display:flex;align-items:center;font-weight:900;font-size:5cqw;white-space:nowrap;overflow:hidden;background:repeating-linear-gradient(-45deg,var(--acc) 0 6cqw,var(--ink) 6cqw 12cqw);color:transparent}.hk11 .t1{top:34cqw;rotate:-8deg;animation:slideL .5s ease .2s both}.hk11 .t2{bottom:34cqw;rotate:6deg;animation:slideR .5s ease .35s both}`,
  props:{ before:"これは", accent:"ダメ", sub:"やりがちなデザインNG" },
  html:p=>`<div class="center hk11 fc" style="gap:3cqw"><div class="tp t1"></div><div class="tp t2"></div><div class="h1 a zi" style="--d:.8s;font-size:13cqw">${p.before}<span class="ac">${p.accent}</span></div><div class="h3 a fu" style="--d:1.1s">${p.sub}</div></div>` },
{ id:148, pal:"lemon", name:"Before/Afterワイプ", desc:"分割線が左から右へ動き、BeforeがAfterに塗り替わる。", loop:4800,
  css:`.hk12 .pn{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3cqw}.hk12 .af{clip-path:inset(0 100% 0 0);animation:hk12 1.4s cubic-bezier(.7,0,.3,1) .8s forwards}@keyframes hk12{to{clip-path:inset(0 0 0 0)}}.hk12 .ln2{position:absolute;top:0;bottom:0;left:0;width:1.2cqw;background:var(--acc);animation:hk12l 1.4s cubic-bezier(.7,0,.3,1) .8s both}@keyframes hk12l{from{left:0}to{left:100%}}`,
  props:{ before:"なんとなく<br>サイト", after:"売れる<br>サイト" },
  html:p=>`<div class="center hk12"><div class="pn"><span class="sm sb">BEFORE</span><span class="h1" style="font-size:12cqw;opacity:.5">${p.before}</span></div><div class="pn af bxa"><span class="sm">AFTER</span><span class="h1" style="font-size:12cqw">${p.after}</span></div><div class="ln2"></div></div>` },
{ id:149, pal:"tanzania", name:"あるある共感", desc:"「あるある」の吹き出しにうなずきマークが連打される。", loop:5000,
  css:`.hk13 .ck{display:flex;gap:2cqw}.hk13 .ck span{width:12cqw;height:12cqw;border-radius:50%;display:grid;place-items:center;font-size:6cqw}`,
  props:{ label:"フリーランスあるある", text:"修正1回のはずが<br>5回目に突入", reaction:"わかる…" },
  html:p=>`<div class="center hk13 fc" style="gap:5cqw"><div class="sm sb a fi">${p.label}</div><div class="bbl bl a pp" style="--d:.3s;font-size:6cqw;align-self:center;max-width:80cqw">${p.text}</div><div class="ck">${[0,1,2,3,4].map(i=>`<span class="bxa a bo" style="${D(1,i,.15)}">${[...p.reaction][0]}</span>`).join("")}</div><div class="h2 a fu" style="--d:1.9s">${p.reaction}</div></div>` },
{ id:150, pal:"maldives", name:"急上昇", desc:"グラフ矢印が画面を突き抜けるように右上へ急上昇する。", loop:4200,
  css:`.hk14 svg{position:absolute;inset:0;width:100%;height:100%}`,
  props:{ line1:"売上", line2:"急上昇", sub:"その理由を解説" },
  html:p=>`<div class="center hk14"><svg viewBox="0 0 90 160" preserveAspectRatio="none"><polyline points="-5,140 20,120 35,128 52,92 66,100 95,20" fill="none" stroke="var(--acc)" stroke-width="4" stroke-linejoin="round" stroke-linecap="round" pathLength="100" class="dw" style="--d:.2s;--du:1.1s"/></svg><div style="position:absolute;left:8cqw;top:28cqw"><div class="h1 a sl" style="--d:1.1s;font-size:13cqw">${p.line1}<br><span class="ac">${p.line2}</span></div><div class="h3 a fu" style="--d:1.4s">${p.sub}</div></div></div>` },
]);
